# Docker Compose override for production
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  traefik:
    command:
      - "--api.dashboard=false"           # Disable dashboard in production
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=WARN"               # Reduce log verbosity
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--providers.docker.constraints=Label(`traefik.stack`,`${TRAEFIK_STACK}`)"
    ports:
      - "${HTTP_PORT:-8090}:80"           # HTTP only, configurable port
      # Dashboard not exposed in production
    labels:
      # Remove dashboard labels for security
      - "traefik.enable=false"
