name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        cache-dependency-path: 'trouvaille-back/pom.xml'
        
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: trouvaille-front/package-lock.json
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Frontend
      run: |
        cd trouvaille-front
        npm ci
        npm run generate:api
        npm run format:check
        npm run lint:check
        npm run type-check
        npm run test:unit 2>/dev/null || echo "No unit tests configured yet"
        npm run build

    - name: Backend
      run: |
        cd trouvaille-back
        ./mvnw clean package
