name: Semantic Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      run: npm audit signatures
      
    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
      
    - name: Create dev version commit
      if: steps.semantic-release.outputs.new_release_published == 'true'
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Get the released version and calculate next dev version
        RELEASED_VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
        
        # Parse version components
        MAJOR=$(echo $RELEASED_VERSION | cut -d. -f1)
        MINOR=$(echo $RELEASED_VERSION | cut -d. -f2)
        PATCH=$(echo $RELEASED_VERSION | cut -d. -f3)
        
        # Increment minor version for next dev cycle
        NEXT_MINOR=$((MINOR + 1))
        DEV_VERSION="${MAJOR}.${NEXT_MINOR}.0-dev"
        
        # Update package.json with dev version
        sed -i "s/\"version\": \".*\"/\"version\": \"$DEV_VERSION\"/" package.json
        
        # Commit the dev version
        git add package.json
        git commit -m "chore: bump version to $DEV_VERSION for next development cycle [skip ci]"
        
        # Push the commit
        git push origin master